apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml

replicas:
  - name: vote
    count: 4

images:
  - name: schoolofdevops/vote
    newTag: v4 # {"$imagepolicy": "flux-system:vote:tag"}

namespace: instavote

commonLabels:
  project: instavote
  env: staging

commonAnnotations:
  supported-by: "danieldwan@gmail.com"
  
configMapGenerator:
  - name: vote-options
    envs:
     - options.env
